[package]
name = "orthoterm"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
reqwest = { version = "0.11", features = ["blocking"] }
anyhow = "1.0"
scraper = "0.17"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
directories = "5.0"
ical = "0.8"
